version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: browset
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydatabase
      - COOKIE_SECRET=ooWIC8ce3SAyZHhZohI23FJWPPBxIRFc
      - PORT=3000
      - ADMIN_USERNAME=admin@example.com
      - ADMIN_PASSWORD=admin
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: browset_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
